// NO AUTHENTICATION

### Register

POST /api/register HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Content-Length: 73

{"username":"peppo", "email":"peppo@polito.it", "password":"peppo"}

### RegisterAdmin

POST /api/admin HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Content-Length: 95

{"username":"Admin", "email":"admin.ga@polito.it", "password":"secure_password"}

### Login

POST /api/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Content-Length: 55

//{"email":"gae@polito.it", "password":"gaetano"}
//{"email": "minicucc.ga@polito.it","password":"minicucc"}
{"email":"admin.ga@polito.it", "password":"secure_password"}


### Logout

GET /api/logout HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Content-Length: 95
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdXJpemlvLm1vQHBvbGl0by5pdCIsImlkIjoiNjQ2MjQ1YTAwNjQ2NDI0OTQ1YTc3ZjdjIiwidXNlcm5hbWUiOiJtYXVyaXppbyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0MjMyNzU5LCJleHAiOjE2ODQyMzYzNTl9.7pIiMXO_VQh0W2aKDR6avQ70Dty4HlIIY20YeMKq_8w;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdXJpemlvLm1vQHBvbGl0by5pdCIsImlkIjoiNjQ2MjQ1YTAwNjQ2NDI0OTQ1YTc3ZjdjIiwidXNlcm5hbWUiOiJtYXVyaXppbyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0MjMyNzU5LCJleHAiOjE2ODQ4Mzc1NTl9.szDQ6NwG2WXNHWULq809LfHYkP2sP_Slqe-zxNkvI-4

// ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
// AUTHENTICATED

### GetCategories

GET /api/categories HTTP/1.1
Host: localhost:3000
Cookie : accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg0NzkxOTUzfQ.-fe8Ni2pDtJ6nxG6hKDiyKNQh75dMbAipNiKMv7mQYg;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg1MzkzMTUzfQ.zE4I5FQ-h7tLYTsenhAxFok62MLe20IawF-tzfdhjLs
#Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc2NTQ5MSwiZXhwIjoxNjg0NzY5MDkxfQ.N5YY0V1jDsaWpJ3ZKMigsH9RArrGr0DVOTWH1ku4niM;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc2NTQ5MSwiZXhwIjoxNjg1MzcwMjkxfQ.iDLyH3mdEtMqRwVSeJjySiiBJsbHWzxvMUAq-HKMUJM


### GetUser

GET /api/users/maurizio HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdXJpemlvLm1vQHBvbGl0by5pdCIsImlkIjoiNjQ2MjQ1YTAwNjQ2NDI0OTQ1YTc3ZjdjIiwidXNlcm5hbWUiOiJtYXVyaXppbyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0MzM1MjI2LCJleHAiOjE2ODQzMzg4MjZ9.m4mNtCHFB1QDB_GHXFyoBhG0k43mJcWdorztXGXs9Qc;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdXJpemlvLm1vQHBvbGl0by5pdCIsImlkIjoiNjQ2MjQ1YTAwNjQ2NDI0OTQ1YTc3ZjdjIiwidXNlcm5hbWUiOiJtYXVyaXppbyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0MzM1MjI2LCJleHAiOjE2ODQ5NDAwMjZ9.CV2kAaIVRH_KPyiVwgLXqNDFMjRDebI856fPGokQGyg

### CreateTransaction
POST /api/users/gae/transactions HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhZUBwb2xpdG8uaXQiLCJpZCI6IjY0NmJjZGQ3ODI3MzYyZWYxMzgwYzIzNSIsInVzZXJuYW1lIjoiZ2FlIiwicm9sZSI6IlJlZ3VsYXIiLCJpYXQiOjE2ODQ3ODY2NjAsImV4cCI6MTY4NDc5MDI2MH0.kr1YYcXWO_wMW6YFI7vELTXRE-ptknDaQ5FI_DucZZg;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhZUBwb2xpdG8uaXQiLCJpZCI6IjY0NmJjZGQ3ODI3MzYyZWYxMzgwYzIzNSIsInVzZXJuYW1lIjoiZ2FlIiwicm9sZSI6IlJlZ3VsYXIiLCJpYXQiOjE2ODQ3ODY2NjAsImV4cCI6MTY4NTM5MTQ2MH0.L72c-9DDq71tZeD6OjtI63upKLMy4od9N-OK5ZoWPcc 
Content-Type: application/json

{"username": "gae", "type": "bici", "amount":"-5"}

### GetTransactionByUser

GET /api/users/Minicucc/transactions?from=2023-05-10&upTo=2023-05-30&min=2000&max=26000 HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbmljdWNjLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ0YmQwMjEzZWU1ZjQ1MGM4NDEzODg2IiwidXNlcm5hbWUiOiJNaW5pY3VjYyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0NzcwNTAxLCJleHAiOjE2ODQ3NzQxMDF9.-uLd4A7sX10dXCI4VNzzG-pCDCsYZEZMJThoKaqb5sc;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbmljdWNjLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ0YmQwMjEzZWU1ZjQ1MGM4NDEzODg2IiwidXNlcm5hbWUiOiJNaW5pY3VjYyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0NzcwNTAxLCJleHAiOjE2ODUzNzUzMDF9.i9jtJtMY-0bQ7aSi528cyvO2XWLOcLkwGrFiFHt5sx8

### DeleteTransaction

DELETE /api/users/maurizio/transactions HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdXJpemlvLm1vQHBvbGl0by5pdCIsImlkIjoiNjQ2MjQ1YTAwNjQ2NDI0OTQ1YTc3ZjdjIiwidXNlcm5hbWUiOiJtYXVyaXppbyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0MzM1MjI2LCJleHAiOjE2ODQzMzg4MjZ9.m4mNtCHFB1QDB_GHXFyoBhG0k43mJcWdorztXGXs9Qc;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdXJpemlvLm1vQHBvbGl0by5pdCIsImlkIjoiNjQ2MjQ1YTAwNjQ2NDI0OTQ1YTc3ZjdjIiwidXNlcm5hbWUiOiJtYXVyaXppbyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0MzM1MjI2LCJleHAiOjE2ODQ5NDAwMjZ9.CV2kAaIVRH_KPyiVwgLXqNDFMjRDebI856fPGokQGyg

{"_id": "646246250646424945a77f84"}

### getTransactionsByUserByCategory

GET /api/users/Minicucc/transactions/category/school HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbmljdWNjLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ0YmQwMjEzZWU1ZjQ1MGM4NDEzODg2IiwidXNlcm5hbWUiOiJNaW5pY3VjYyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0NzcwNTAxLCJleHAiOjE2ODQ3NzQxMDF9.-uLd4A7sX10dXCI4VNzzG-pCDCsYZEZMJThoKaqb5sc;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbmljdWNjLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ0YmQwMjEzZWU1ZjQ1MGM4NDEzODg2IiwidXNlcm5hbWUiOiJNaW5pY3VjYyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0NzcwNTAxLCJleHAiOjE2ODUzNzUzMDF9.i9jtJtMY-0bQ7aSi528cyvO2XWLOcLkwGrFiFHt5sx8

### CreateGroup

POST /api/groups HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"name": "gruppo","memberEmails":["gae.ga@polito.it","domenico.ga@polito.it"]}


### getGroup

GET /api/groups/:name HTTP/1.1
Host: localhost:3000

### getTransactionsByGroup

GET /api/groups/gruppo_prova/transactions HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbmljdWNjLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ0YmQwMjEzZWU1ZjQ1MGM4NDEzODg2IiwidXNlcm5hbWUiOiJNaW5pY3VjYyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0NzcyOTgxLCJleHAiOjE2ODQ3NzY1ODF9.9PgWbyI6cGvp9bPFLc9eSDzd9iZJvHlxtRn3D7JFIBc;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbmljdWNjLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ0YmQwMjEzZWU1ZjQ1MGM4NDEzODg2IiwidXNlcm5hbWUiOiJNaW5pY3VjYyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0NzcyOTgxLCJleHAiOjE2ODUzNzc3ODF9.6yrsfYjy30JWyuQzL00xUSNpAz0GB3KUonT_g7hsOGU 

### getTransactionsByGroupByCategory

GET /api/groups/gruppo_prova/transactions/category/school HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbmljdWNjLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ0YmQwMjEzZWU1ZjQ1MGM4NDEzODg2IiwidXNlcm5hbWUiOiJNaW5pY3VjYyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0NzcyOTgxLCJleHAiOjE2ODQ3NzY1ODF9.9PgWbyI6cGvp9bPFLc9eSDzd9iZJvHlxtRn3D7JFIBc;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbmljdWNjLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ0YmQwMjEzZWU1ZjQ1MGM4NDEzODg2IiwidXNlcm5hbWUiOiJNaW5pY3VjYyIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNjg0NzcyOTgxLCJleHAiOjE2ODUzNzc3ODF9.6yrsfYjy30JWyuQzL00xUSNpAz0GB3KUonT_g7hsOGU 

### addToGroup

PATCH /api/groups/gruppo_prova/add HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"name": "gruppo_prova","memberEmails":["peppo@polito.it"]}
### removeFromGroup

PATCH /api/groups/gruppo/remove HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"users":["gae.ga@polito.it"]}


// ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
// ADMIN EXCLUSIVE

### createCategory

POST /api/categories HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg0NzkxOTUzfQ.-fe8Ni2pDtJ6nxG6hKDiyKNQh75dMbAipNiKMv7mQYg;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg1MzkzMTUzfQ.zE4I5FQ-h7tLYTsenhAxFok62MLe20IawF-tzfdhjLs
Content-Type: application/json
Content-Length: 34

{"type":"vespa", "color":"black"}

### updateCategory

PATCH /api/categories/vespa HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg0NzkxOTUzfQ.-fe8Ni2pDtJ6nxG6hKDiyKNQh75dMbAipNiKMv7mQYg;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg1MzkzMTUzfQ.zE4I5FQ-h7tLYTsenhAxFok62MLe20IawF-tzfdhjLs
Content-Type: application/json

{"type":"vespaa", "color":"black"}


### deleteCategory

DELETE /api/categories HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg0NzkxOTUzfQ.-fe8Ni2pDtJ6nxG6hKDiyKNQh75dMbAipNiKMv7mQYg;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg1MzkzMTUzfQ.zE4I5FQ-h7tLYTsenhAxFok62MLe20IawF-tzfdhjLs
Content-Type: application/json

{"types" :["bici"] }

### getAllTransactions

GET /api/transactions HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg0NzkxOTUzfQ.-fe8Ni2pDtJ6nxG6hKDiyKNQh75dMbAipNiKMv7mQYg;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg1MzkzMTUzfQ.zE4I5FQ-h7tLYTsenhAxFok62MLe20IawF-tzfdhjLs
### deleteTransactions

DELETE /api/transactions HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"_ids" :[" "] }

### getTransactionsByUser

GET /api/transactions/users/maurizio HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc2NTQ5MSwiZXhwIjoxNjg0NzY5MDkxfQ.N5YY0V1jDsaWpJ3ZKMigsH9RArrGr0DVOTWH1ku4niM;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc2NTQ5MSwiZXhwIjoxNjg1MzcwMjkxfQ.iDLyH3mdEtMqRwVSeJjySiiBJsbHWzxvMUAq-HKMUJM


### getTransactionsByUserByCategory

GET /api/transactions/users/:username/category/:category HTTP/1.1
Host: localhost:3000

### getGroups

GET /api/groups HTTP/1.1
Host: localhost:3000

### deleteGroup

DELETE /api/groups HTTP/1.1
Host: localhost:3000

### getUsers

GET /api/users HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg0NzkxOTUzfQ.-fe8Ni2pDtJ6nxG6hKDiyKNQh75dMbAipNiKMv7mQYg;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg1MzkzMTUzfQ.zE4I5FQ-h7tLYTsenhAxFok62MLe20IawF-tzfdhjLs
### deleteUser

DELETE /api/users HTTP/1.1
Host: localhost:3000
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg0NzkxOTUzfQ.-fe8Ni2pDtJ6nxG6hKDiyKNQh75dMbAipNiKMv7mQYg;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLmdhQHBvbGl0by5pdCIsImlkIjoiNjQ2ODlmZmFhODBiNDg5YzNlODBiMWNkIiwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY4NDc4ODM1MywiZXhwIjoxNjg1MzkzMTUzfQ.zE4I5FQ-h7tLYTsenhAxFok62MLe20IawF-tzfdhjLs
Content-Type: application/json

{"email": "peppo@polito.it"}

### getTransactionsByGroup

GET /api/transactions/groups/:name HTTP/1.1
Host: localhost:3000

### getTransactionsByGroupByCategory

GET /api/transactions/groups/:name/category/:category HTTP/1.1
Host: localhost:3000

### addToGroup

PATCH /api/groups/:name/insert HTTP/1.1
Host: localhost:3000

### removeFromGroup

PATCH /api/groups/:name/pull HTTP/1.1
Host: localhost:3000